#!/bin/bash
# Insert the file in the /usr/bin folder and type “updatenrgrecords”,
# To run the script of updating the website from the git

sleep 3
echo updatenrgrecords: Updating NRG Records Site
sleep 3
cd /home/ubuntu/nrgRecords.cf
echo updatenrgrecords: Stopping gunicorn process
sudo service gunicorn stop
echo updatenrgrecords: Pulling from the git
git pull
echo updatenrgrecords: Starting gunicorn process...
sudo service gunicorn start
echo updatenrgrecords: Successfully updated the NRG Records website!
